// backend/assets/js/react/context/ProcessContext.jsx
import React, { createContext, useContext, useReducer, useCallback, useEffect } from "react";
import { api } from "../utils/api";
import { useUpload } from "../hooks/useUpload";
import { useChannel } from "../hooks/useChannel";

// Initial state
const initialState = {
  // Upload
  file: null,
  s3Key: null,
  filename: null,
  uploadProgress: 0,
  uploadState: "idle", // idle, uploading, ready, error

  // Presets
  presets: ["podcast", "broadcast", "gentle"],
  selectedPreset: "podcast",

  // Job
  job: null,

  // Error
  error: null,
};

// Action types
const ACTIONS = {
  SET_FILE: "SET_FILE",
  SET_UPLOAD_PROGRESS: "SET_UPLOAD_PROGRESS",
  SET_UPLOAD_STATE: "SET_UPLOAD_STATE",
  SET_UPLOAD_COMPLETE: "SET_UPLOAD_COMPLETE",
  SET_PRESETS: "SET_PRESETS",
  SELECT_PRESET: "SELECT_PRESET",
  SET_JOB: "SET_JOB",
  UPDATE_JOB: "UPDATE_JOB",
  SET_ERROR: "SET_ERROR",
  RESET: "RESET",
};

// Reducer
function reducer(state, action) {
  switch (action.type) {
    case ACTIONS.SET_FILE:
      return {
        ...state,
        file: action.file,
        filename: action.file?.name || null,
        uploadState: "idle",
        error: null,
      };

    case ACTIONS.SET_UPLOAD_PROGRESS:
      return {
        ...state,
        uploadProgress: action.progress,
        uploadState: "uploading",
      };

    case ACTIONS.SET_UPLOAD_STATE:
      return {
        ...state,
        uploadState: action.uploadState,
      };

    case ACTIONS.SET_UPLOAD_COMPLETE:
      return {
        ...state,
        s3Key: action.s3Key,
        filename: action.filename,
        uploadProgress: 100,
        uploadState: "ready",
      };

    case ACTIONS.SET_PRESETS:
      return {
        ...state,
        presets: action.presets,
      };

    case ACTIONS.SELECT_PRESET:
      return {
        ...state,
        selectedPreset: action.preset,
      };

    case ACTIONS.SET_JOB:
      return {
        ...state,
        job: action.job,
        error: null,
      };

    case ACTIONS.UPDATE_JOB:
      return {
        ...state,
        job: action.job,
      };

    case ACTIONS.SET_ERROR:
      return {
        ...state,
        error: action.error,
      };

    case ACTIONS.RESET:
      return {
        ...initialState,
        presets: state.presets,
        selectedPreset: state.selectedPreset,
      };

    default:
      return state;
  }
}

// Context
const ProcessContext = createContext(null);

// Provider
export function ProcessProvider({ children }) {
  const [state, dispatch] = useReducer(reducer, initialState);
  const { upload, progress, uploading, error: uploadError, reset: resetUpload } = useUpload();

  // Update upload progress
  useEffect(() => {
    if (uploading) {
      dispatch({ type: ACTIONS.SET_UPLOAD_PROGRESS, progress });
    }
  }, [progress, uploading]);

  // Handle upload errors
  useEffect(() => {
    if (uploadError) {
      dispatch({ type: ACTIONS.SET_ERROR, error: uploadError });
      dispatch({ type: ACTIONS.SET_UPLOAD_STATE, uploadState: "error" });
    }
  }, [uploadError]);

  // Job update handler for channel
  const handleJobUpdate = useCallback((job) => {
    dispatch({ type: ACTIONS.UPDATE_JOB, job });
  }, []);

  // Connect to job channel when job exists
  useChannel(state.job?.id, handleJobUpdate);

  // Load presets on mount
  useEffect(() => {
    api.getPresets()
      .then(({ presets }) => {
        dispatch({ type: ACTIONS.SET_PRESETS, presets });
      })
      .catch((err) => {
        console.error("Failed to load presets:", err);
      });
  }, []);

  // Actions
  const selectFile = useCallback((file) => {
    dispatch({ type: ACTIONS.SET_FILE, file });
  }, []);

  const uploadFile = useCallback(async (file) => {
    dispatch({ type: ACTIONS.SET_UPLOAD_STATE, uploadState: "uploading" });
    try {
      const { key, filename } = await upload(file);
      dispatch({ type: ACTIONS.SET_UPLOAD_COMPLETE, s3Key: key, filename });
      return { key, filename };
    } catch (err) {
      dispatch({ type: ACTIONS.SET_ERROR, error: err.message });
      dispatch({ type: ACTIONS.SET_UPLOAD_STATE, uploadState: "error" });
      throw err;
    }
  }, [upload]);

  const selectPreset = useCallback((preset) => {
    dispatch({ type: ACTIONS.SELECT_PRESET, preset });
  }, []);

  const submitJob = useCallback(async () => {
    if (!state.s3Key || !state.filename) {
      dispatch({ type: ACTIONS.SET_ERROR, error: "Please upload a file first" });
      return;
    }

    try {
      const job = await api.createJob(state.s3Key, state.filename, state.selectedPreset);
      dispatch({ type: ACTIONS.SET_JOB, job });
    } catch (err) {
      dispatch({ type: ACTIONS.SET_ERROR, error: err.message });
    }
  }, [state.s3Key, state.filename, state.selectedPreset]);

  const cancelJob = useCallback(async () => {
    if (state.job?.id) {
      try {
        await api.cancelJob(state.job.id);
      } catch (err) {
        console.error("Failed to cancel job:", err);
      }
    }
    resetUpload();
    dispatch({ type: ACTIONS.RESET });
  }, [state.job, resetUpload]);

  const clearError = useCallback(() => {
    dispatch({ type: ACTIONS.SET_ERROR, error: null });
  }, []);

  const reset = useCallback(() => {
    resetUpload();
    dispatch({ type: ACTIONS.RESET });
  }, [resetUpload]);

  const value = {
    state,
    selectFile,
    uploadFile,
    selectPreset,
    submitJob,
    cancelJob,
    clearError,
    reset,
  };

  return (
    <ProcessContext.Provider value={value}>
      {children}
    </ProcessContext.Provider>
  );
}

// Hook
export function useProcess() {
  const context = useContext(ProcessContext);
  if (!context) {
    throw new Error("useProcess must be used within a ProcessProvider");
  }
  return context;
}

// backend/assets/js/solid/context/ProcessContext.jsx
import { createContext, useContext, createSignal, createEffect, onMount, onCleanup } from "solid-js";
import { createStore } from "solid-js/store";
import { Socket } from "phoenix";
import { api } from "../utils/api";

const ProcessContext = createContext();

export function ProcessProvider(props) {
  const [store, setStore] = createStore({
    file: null,
    s3Key: null,
    filename: null,
    uploadProgress: 0,
    uploadState: "idle", // idle, uploading, ready, error
    presets: ["podcast", "broadcast", "gentle"],
    selectedPreset: "podcast",
    job: null,
    error: null,
  });

  // Channel connection - managed outside reactive system
  let socket = null;
  let channel = null;

  // Load presets on mount
  onMount(async () => {
    try {
      const { presets } = await api.getPresets();
      setStore("presets", presets);
    } catch (err) {
      console.error("Failed to load presets:", err);
    }
  });

  // Cleanup on component unmount
  onCleanup(() => {
    if (channel) channel.leave();
    if (socket) socket.disconnect();
  });

  // Connect to job channel when job.id changes (fine-grained tracking)
  createEffect(() => {
    const jobId = store.job?.id;  // Track only job.id, not entire job object

    // Clean up previous connection
    if (channel) {
      channel.leave();
      channel = null;
    }
    if (socket) {
      socket.disconnect();
      socket = null;
    }

    // Connect if we have a job and token
    if (jobId && window.userToken) {
      socket = new Socket("/socket", {
        params: { token: window.userToken }
      });
      socket.connect();

      channel = socket.channel(`job:${jobId}`, {});
      channel.join()
        .receive("ok", () => console.log("Joined job:" + jobId))
        .receive("error", (e) => console.error("Join failed", e));

      channel.on("job_updated", (payload) => {
        setStore("job", payload.job);
      });
    }
  });

  async function uploadFile(file) {
    setStore({
      file,
      filename: file.name,
      uploadState: "uploading",
      uploadProgress: 0,
      error: null,
    });

    try {
      const { url, key } = await api.presignUpload(file.name);

      await new Promise((resolve, reject) => {
        const xhr = new XMLHttpRequest();

        xhr.upload.addEventListener("progress", (e) => {
          if (e.lengthComputable) {
            setStore("uploadProgress", Math.round((e.loaded / e.total) * 100));
          }
        });

        xhr.addEventListener("load", () => {
          if (xhr.status >= 200 && xhr.status < 300) {
            resolve();
          } else {
            reject(new Error(`Upload failed: ${xhr.status}`));
          }
        });

        xhr.addEventListener("error", () => reject(new Error("Upload failed")));

        xhr.open("PUT", url, true);
        xhr.setRequestHeader("Content-Type", file.type || "application/octet-stream");
        xhr.send(file);
      });

      setStore({ s3Key: key, uploadState: "ready" });
    } catch (err) {
      setStore({ error: err.message, uploadState: "error" });
    }
  }

  function selectPreset(preset) {
    setStore("selectedPreset", preset);
  }

  async function submitJob() {
    if (!store.s3Key || !store.filename) {
      setStore("error", "Please upload a file first");
      return;
    }

    try {
      const job = await api.createJob(store.s3Key, store.filename, store.selectedPreset);
      setStore({ job, error: null });
    } catch (err) {
      setStore("error", err.message);
    }
  }

  async function cancelJob() {
    if (store.job?.id) {
      try {
        await api.cancelJob(store.job.id);
      } catch (err) {
        console.error("Failed to cancel:", err);
      }
    }
    reset();
  }

  function clearError() {
    setStore("error", null);
  }

  function reset() {
    setStore({
      file: null,
      s3Key: null,
      filename: null,
      uploadProgress: 0,
      uploadState: "idle",
      job: null,
      error: null,
    });
  }

  const value = {
    store,
    uploadFile,
    selectPreset,
    submitJob,
    cancelJob,
    clearError,
    reset,
  };

  return (
    <ProcessContext.Provider value={value}>
      {props.children}
    </ProcessContext.Provider>
  );
}

export function useProcess() {
  const ctx = useContext(ProcessContext);
  if (!ctx) throw new Error("useProcess must be used within ProcessProvider");
  return ctx;
}
